// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $CreateItem from "./routes/CreateItem.jsx";
import * as $_404 from "./routes/_404.jsx";
import * as $_app from "./routes/_app.jsx";
import * as $index from "./routes/index.jsx";
import * as $items from "./routes/items.jsx";
import * as $Counter from "./islands/Counter.jsx"; // Adjust the file extension if necessary

const manifest = {
  routes: {
    "./routes/CreateItem.jsx": $CreateItem,
    "./routes/_404.jsx": $_404,
    "./routes/_app.jsx": $_app,
    "./routes/index.jsx": $index,
    "./routes/items.jsx": $items,
  },
  islands: {
    "./islands/Counter.jsx": $Counter, // Adjust the file extension if necessary
  },
  baseUrl: import.meta.url,
};

export default manifest;
